// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudySphere.Data;

#nullable disable

namespace StudySphere.Migrations
{
    [DbContext(typeof(StudySphereDbContext))]
    [Migration("20260917163228_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudySphere.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<string>("Designation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AdminId");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            AdminId = 9,
                            Designation = "System Administrator"
                        });
                });

            modelBuilder.Entity("StudySphere.Models.Announcement", b =>
                {
                    b.Property<int>("AnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnnouncementId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("AnnouncementId");

                    b.HasIndex("CourseId");

                    b.HasIndex("InstructorId");

                    b.ToTable("Announcements");

                    b.HasData(
                        new
                        {
                            AnnouncementId = 1,
                            CourseId = 1,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 6,
                            IsPublished = true,
                            Message = "Welcome to the ASP.NET Core MVC course.",
                            Title = "Welcome to ASP.NET Core MVC"
                        },
                        new
                        {
                            AnnouncementId = 2,
                            CourseId = 1,
                            CreatedAt = new DateTime(2026, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 6,
                            IsPublished = true,
                            Message = "Assignment 1 has been published.",
                            Title = "Assignment 1"
                        },
                        new
                        {
                            AnnouncementId = 3,
                            CourseId = 2,
                            CreatedAt = new DateTime(2026, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 7,
                            IsPublished = true,
                            Message = "Practice the Spring Boot concepts covered in the lectures.",
                            Title = "Spring Boot Practice"
                        });
                });

            modelBuilder.Entity("StudySphere.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("Level")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CourseId");

                    b.HasIndex("InstructorId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            Category = "Web Development",
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Learn ASP.NET Core MVC from basics to advanced concepts.",
                            InstructorId = 6,
                            Level = "Intermediate",
                            Price = 1499m,
                            Status = "Approved",
                            ThumbnailUrl = "/images/courses/aspnet.jpg",
                            Title = "ASP.NET Core MVC"
                        },
                        new
                        {
                            CourseId = 2,
                            Category = "Programming",
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Learn Java programming and backend development fundamentals.",
                            InstructorId = 7,
                            Level = "Beginner",
                            Price = 999m,
                            Status = "Approved",
                            ThumbnailUrl = "/images/courses/java.jpg",
                            Title = "Java Programming"
                        },
                        new
                        {
                            CourseId = 3,
                            Category = "Programming",
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Learn C# programming from fundamentals to advanced concepts.",
                            InstructorId = 6,
                            Level = "Beginner",
                            Price = 799m,
                            Status = "Pending",
                            ThumbnailUrl = "/images/courses/csharp.jpg",
                            Title = "Complete C# Programming"
                        },
                        new
                        {
                            CourseId = 4,
                            Category = "Database",
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Learn database concepts, SQL and database design.",
                            InstructorId = 8,
                            Level = "Intermediate",
                            Price = 1199m,
                            Status = "Pending",
                            ThumbnailUrl = "/images/courses/database.jpg",
                            Title = "Database Management System"
                        },
                        new
                        {
                            CourseId = 5,
                            Category = "Web Development",
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Learn HTML, CSS and basic web design concepts.",
                            InstructorId = 7,
                            Level = "Beginner",
                            Price = 599m,
                            Status = "Rejected",
                            ThumbnailUrl = "/images/courses/webdesign.jpg",
                            Title = "Basic Web Design"
                        });
                });

            modelBuilder.Entity("StudySphere.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Progress")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            EnrollmentId = 1,
                            CourseId = 1,
                            EnrolledAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 75m,
                            Status = "Active",
                            StudentId = 1
                        },
                        new
                        {
                            EnrollmentId = 2,
                            CourseId = 1,
                            EnrolledAt = new DateTime(2026, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 50m,
                            Status = "Active",
                            StudentId = 2
                        },
                        new
                        {
                            EnrollmentId = 3,
                            CompletedAt = new DateTime(2026, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 2,
                            EnrolledAt = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 100m,
                            Status = "Completed",
                            StudentId = 3
                        },
                        new
                        {
                            EnrollmentId = 4,
                            CourseId = 1,
                            EnrolledAt = new DateTime(2026, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 40m,
                            Status = "Active",
                            StudentId = 4
                        });
                });

            modelBuilder.Entity("StudySphere.Models.Instructor", b =>
                {
                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("AreaOfExpertise")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ProfessionalTitle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProfileImage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Qualification")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("InstructorId");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            InstructorId = 6,
                            AreaOfExpertise = "Web Development",
                            Bio = "Experienced instructor in web and backend development.",
                            ProfessionalTitle = "Senior Software Developer",
                            Qualification = "B.Tech Computer Engineering"
                        },
                        new
                        {
                            InstructorId = 7,
                            AreaOfExpertise = "Java and Spring Boot",
                            Bio = "Experienced Java and backend development instructor.",
                            ProfessionalTitle = "Java Developer",
                            Qualification = "M.Tech Computer Science"
                        },
                        new
                        {
                            InstructorId = 8,
                            AreaOfExpertise = "Database Management",
                            Bio = "Experienced database management instructor.",
                            ProfessionalTitle = "Database Specialist",
                            Qualification = "M.Tech Information Technology"
                        });
                });

            modelBuilder.Entity("StudySphere.Models.LiveLecture", b =>
                {
                    b.Property<int>("LiveLectureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LiveLectureId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("MeetingUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("LiveLectureId");

                    b.HasIndex("CourseId");

                    b.HasIndex("InstructorId");

                    b.ToTable("LiveLectures");

                    b.HasData(
                        new
                        {
                            LiveLectureId = 1,
                            CourseId = 1,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Live lecture about controllers in ASP.NET Core MVC.",
                            EndTime = new DateTime(2026, 9, 18, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 6,
                            MeetingUrl = "https://meet.example.com/aspnet",
                            StartTime = new DateTime(2026, 9, 18, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Scheduled",
                            Title = "ASP.NET Core MVC - Controllers"
                        },
                        new
                        {
                            LiveLectureId = 2,
                            CourseId = 2,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Live lecture about creating REST APIs using Spring Boot.",
                            EndTime = new DateTime(2026, 9, 19, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 7,
                            MeetingUrl = "https://meet.example.com/spring",
                            StartTime = new DateTime(2026, 9, 19, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Scheduled",
                            Title = "Spring Boot REST API"
                        });
                });

            modelBuilder.Entity("StudySphere.Models.Material", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int?>("DurationInMinutes")
                        .HasColumnType("int");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MaterialId");

                    b.HasIndex("CourseId");

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            MaterialId = 1,
                            CourseId = 1,
                            Description = "Introduction to ASP.NET Core MVC.",
                            DisplayOrder = 1,
                            DurationInMinutes = 25,
                            FileUrl = "/materials/aspnet/introduction.mp4",
                            IsPublished = true,
                            MaterialType = "Video",
                            Title = "Introduction to ASP.NET Core MVC",
                            UploadedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaterialId = 2,
                            CourseId = 1,
                            Description = "PDF notes explaining MVC architecture.",
                            DisplayOrder = 2,
                            FileUrl = "/materials/aspnet/mvc-notes.pdf",
                            IsPublished = true,
                            MaterialType = "PDF",
                            Title = "MVC Architecture Notes",
                            UploadedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaterialId = 3,
                            CourseId = 1,
                            Description = "Understanding controllers and action methods.",
                            DisplayOrder = 3,
                            DurationInMinutes = 30,
                            FileUrl = "/materials/aspnet/controllers.mp4",
                            IsPublished = true,
                            MaterialType = "Video",
                            Title = "Controllers in ASP.NET Core",
                            UploadedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaterialId = 4,
                            CourseId = 2,
                            Description = "Introduction to Spring Boot.",
                            DisplayOrder = 1,
                            DurationInMinutes = 35,
                            FileUrl = "/materials/java/spring-introduction.mp4",
                            IsPublished = true,
                            MaterialType = "Video",
                            Title = "Spring Boot Introduction",
                            UploadedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaterialId = 5,
                            CourseId = 2,
                            Description = "Spring Boot learning notes.",
                            DisplayOrder = 2,
                            FileUrl = "/materials/java/spring-notes.pdf",
                            IsPublished = false,
                            MaterialType = "PDF",
                            Title = "Spring Boot Notes",
                            UploadedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("StudySphere.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EnrollmentNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProfileImage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Bio = "Computer Engineering student.",
                            EnrollmentNo = "STU001"
                        },
                        new
                        {
                            StudentId = 2,
                            Bio = "Computer Engineering student.",
                            EnrollmentNo = "STU002"
                        },
                        new
                        {
                            StudentId = 3,
                            Bio = "Computer Engineering student.",
                            EnrollmentNo = "STU003"
                        },
                        new
                        {
                            StudentId = 4,
                            Bio = "Computer Engineering student.",
                            EnrollmentNo = "STU004"
                        },
                        new
                        {
                            StudentId = 5,
                            Bio = "Computer Engineering student.",
                            EnrollmentNo = "STU005"
                        });
                });

            modelBuilder.Entity("StudySphere.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "student1@studysphere.com",
                            FullName = "Student One",
                            IsActive = true,
                            PasswordHash = "password",
                            Phone = "9876543201",
                            Role = "Student"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "student2@studysphere.com",
                            FullName = "Student Two",
                            IsActive = true,
                            PasswordHash = "password",
                            Phone = "9876543202",
                            Role = "Student"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "student3@studysphere.com",
                            FullName = "Student Three",
                            IsActive = true,
                            PasswordHash = "password",
                            Phone = "9876543203",
                            Role = "Student"
                        },
                        new
                        {
                            UserId = 4,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "student4@studysphere.com",
                            FullName = "Student Four",
                            IsActive = true,
                            PasswordHash = "password",
                            Phone = "9876543204",
                            Role = "Student"
                        },
                        new
                        {
                            UserId = 5,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "student5@studysphere.com",
                            FullName = "Student Five",
                            IsActive = true,
                            PasswordHash = "password",
                            Phone = "9876543205",
                            Role = "Student"
                        },
                        new
                        {
                            UserId = 6,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "instructor1@studysphere.com",
                            FullName = "Instructor One",
                            IsActive = true,
                            PasswordHash = "password",
                            Phone = "9876543210",
                            Role = "Instructor"
                        },
                        new
                        {
                            UserId = 7,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "instructor2@studysphere.com",
                            FullName = "Instructor Two",
                            IsActive = true,
                            PasswordHash = "password",
                            Phone = "9876543211",
                            Role = "Instructor"
                        },
                        new
                        {
                            UserId = 8,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "instructor3@studysphere.com",
                            FullName = "Instructor Three",
                            IsActive = true,
                            PasswordHash = "password",
                            Phone = "9876543212",
                            Role = "Instructor"
                        },
                        new
                        {
                            UserId = 9,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@studysphere.com",
                            FullName = "System Admin",
                            IsActive = true,
                            PasswordHash = "password",
                            Phone = "9876543213",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("StudySphere.Models.Admin", b =>
                {
                    b.HasOne("StudySphere.Models.User", "User")
                        .WithOne("Admin")
                        .HasForeignKey("StudySphere.Models.Admin", "AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudySphere.Models.Announcement", b =>
                {
                    b.HasOne("StudySphere.Models.Course", "Course")
                        .WithMany("Announcements")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudySphere.Models.Instructor", "Instructor")
                        .WithMany("Announcements")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("StudySphere.Models.Course", b =>
                {
                    b.HasOne("StudySphere.Models.Instructor", "Instructor")
                        .WithMany("Courses")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("StudySphere.Models.Enrollment", b =>
                {
                    b.HasOne("StudySphere.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudySphere.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudySphere.Models.Instructor", b =>
                {
                    b.HasOne("StudySphere.Models.User", "User")
                        .WithOne("Instructor")
                        .HasForeignKey("StudySphere.Models.Instructor", "InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudySphere.Models.LiveLecture", b =>
                {
                    b.HasOne("StudySphere.Models.Course", "Course")
                        .WithMany("LiveLectures")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudySphere.Models.Instructor", "Instructor")
                        .WithMany("LiveLectures")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("StudySphere.Models.Material", b =>
                {
                    b.HasOne("StudySphere.Models.Course", "Course")
                        .WithMany("Materials")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("StudySphere.Models.Student", b =>
                {
                    b.HasOne("StudySphere.Models.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("StudySphere.Models.Student", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudySphere.Models.Course", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("Enrollments");

                    b.Navigation("LiveLectures");

                    b.Navigation("Materials");
                });

            modelBuilder.Entity("StudySphere.Models.Instructor", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("Courses");

                    b.Navigation("LiveLectures");
                });

            modelBuilder.Entity("StudySphere.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("StudySphere.Models.User", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("Instructor");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
